<?php
/**
 * @file
 * Code for the govCMS CKAN module.
 */

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function govcms_ckan_form_node_type_form_alter(&$form, Drupal\Core\Form\FormStateInterface $form_state) {
  if (empty($form['type'])) {
    return;
  }

  $config = \Drupal::config('govcms_ckan.settings');

  $form['ckan_graph'] = [
    '#title' => t('CKAN Graph'),
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#group' => 'additional_settings',
    '#weight' => -100,
  ];

  $form['ckan_graph']['govcms_ckan_graph_node'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable govCMS CKAN graph functionality.'),
    '#description' => t('Allows this content type to be displayed as a CKAN Graph.'),
    '#default_value' => $config->get('graph_node_' . $form['#node_type']->type, FALSE),
  ];
}
